### ISSUE TITLE
可能为计算同时拥有免疫和吸血套时出现错误

### ISSUE THREAD

**Issue by CSOLYOO** [jayscorpio/epic7#1]
`Start calculation round 0
Start calculation round 1
Start calculation round 2
Process Process-21:
Traceback (most recent call last):
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 475, in calc_benchmark_group
    result = calc_benchmark_group_on_items_set(
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 692, in calc_benchmark_group_on_items_set
    if hero.chk_thresholds():
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 89, in chk_thresholds
    status = self.get_status()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 170, in get_status
    ctr_sets[itm['set']] += 1
KeyError: None
Process Process-22:
Traceback (most recent call last):
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 475, in calc_benchmark_group
    result = calc_benchmark_group_on_items_set(
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 692, in calc_benchmark_group_on_items_set
    if hero.chk_thresholds():
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 89, in chk_thresholds
    status = self.get_status()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 170, in get_status
    ctr_sets[itm['set']] += 1
KeyError: None
Process Process-23:
Traceback (most recent call last):
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 475, in calc_benchmark_group
    result = calc_benchmark_group_on_items_set(
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 692, in calc_benchmark_group_on_items_set
    if hero.chk_thresholds():
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 89, in chk_thresholds
    status = self.get_status()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 170, in get_status
    ctr_sets[itm['set']] += 1
KeyError: None
Process Process-24:
Traceback (most recent call last):
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 475, in calc_benchmark_group
    result = calc_benchmark_group_on_items_set(
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 692, in calc_benchmark_group_on_items_set
    if hero.chk_thresholds():
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 89, in chk_thresholds
    status = self.get_status()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 170, in get_status
    ctr_sets[itm['set']] += 1
KeyError: None
Process Process-25:
Process Process-26:
Process Process-27:
Process Process-28:
Process Process-29:
Process Process-30:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 475, in calc_benchmark_group
    result = calc_benchmark_group_on_items_set(
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 475, in calc_benchmark_group
    result = calc_benchmark_group_on_items_set(
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 475, in calc_benchmark_group
    result = calc_benchmark_group_on_items_set(
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 692, in calc_benchmark_group_on_items_set
    if hero.chk_thresholds():
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 692, in calc_benchmark_group_on_items_set
    if hero.chk_thresholds():
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 692, in calc_benchmark_group_on_items_set
    if hero.chk_thresholds():
  File "C:\Users\nethe\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 89, in chk_thresholds
    status = self.get_status()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 89, in chk_thresholds
    status = self.get_status()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 475, in calc_benchmark_group
    result = calc_benchmark_group_on_items_set(
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 475, in calc_benchmark_group
    result = calc_benchmark_group_on_items_set(
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 89, in chk_thresholds
    status = self.get_status()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 475, in calc_benchmark_group
    result = calc_benchmark_group_on_items_set(
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 170, in get_status
    ctr_sets[itm['set']] += 1
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 170, in get_status
    ctr_sets[itm['set']] += 1
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 692, in calc_benchmark_group_on_items_set
    if hero.chk_thresholds():
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 692, in calc_benchmark_group_on_items_set
    if hero.chk_thresholds():
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 170, in get_status
    ctr_sets[itm['set']] += 1
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 692, in calc_benchmark_group_on_items_set
    if hero.chk_thresholds():
KeyError: None
KeyError: None
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 89, in chk_thresholds
    status = self.get_status()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 89, in chk_thresholds
    status = self.get_status()
KeyError: None
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 89, in chk_thresholds
    status = self.get_status()
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 170, in get_status
    ctr_sets[itm['set']] += 1
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 170, in get_status
    ctr_sets[itm['set']] += 1
  File "D:\Download Files\epic7-master\epic7-master\v2.py", line 170, in get_status
    ctr_sets[itm['set']] += 1`

XLSX文档
[data.xlsx](https://github.com/jayscorpio/epic7/files/5646896/data.xlsx)

实在不知道这个None是哪里的错误

**Comment by CSOLYOO** [comment]
![Uploading image.png…]()

**Comment by CSOLYOO** [comment]
https://pastebin.ubuntu.com/p/8qJ9dqYcYZ/

**Comment by CSOLYOO** [comment]
把吸血套去了就好了...不知道是什么问题... 我明明有一套完整的吸血+免疫。难道是优先条件的问题？

**Comment by CSOLYOO** [comment]
看起来是我的装备太菜。系统判断我的装备不配凑出他的条件（

**Comment by jayscorpio** [comment]
> 看起来是我的装备太菜。系统判断我的装备不配凑出他的条件（

应该是有个装备数据里的套装写错了，我看了excel表，可能问题出在ring的19行，有个多出来的1，可能导致载入了一个错误的数据

**Comment by jayscorpio** [comment]
#4 我在这个fix里加了一点检错机制

**Comment by jayscorpio** [comment]
今天更新的版本改变了数据导入的格式，原来的excel表格式已经不兼容了，我就没拿你的excel再验证了
不过旧的格式应该很容易迁移到新格式，主要就是把数据拆分开来了

**Comment by CSOLYOO** [comment]
好的。等待您的新版本~ 光讨伐的属性先弄一个占位符进去？和免疫吸血一样的算法

**Comment by jayscorpio** [comment]
> 好的。等待您的新版本~ 光讨伐的属性先弄一个占位符进去？和免疫吸血一样的算法

可以拉取最新代码试试了。要加光讨伐套餐的话只要在Plans里增加新的表或者直接在某个Plan里新增一个sheet填写条件就可以了
